/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dcolor */

#ifndef _Included_Dcolor
#define _Included_Dcolor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dcolor
 * Method:    process
 * Signature: (Lorg/opencv/core/Mat;FFF)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_Dcolor_process
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
